name: build

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]
    steps:
    - uses: actions/checkout@v5
    - name: Install BLAS and LAPACK
      run: sudo apt-get install -y libopenblas-dev liblapacke-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  build-win:
    runs-on: windows-latest
    name: Ruby 3.4 (Windows)
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Install OpenBLAS and LAPACK
        run: |
          pacman -Syu
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-openblas mingw-w64-ucrt-x86_64-lapack
      - name: Install numo-narray
        run: |
          gem install specific_install
          gem specific_install -l 'https://github.com/ruby-numo/numo-narray.git'
      - name: Run the default task
        run: |
          bundle install
          bundle exec rake compile -- --with-opt-lib="C:\hostedtoolcache\windows\Ruby\3.4.4\x64\msys64\ucrt64\lib" --with-opt-include="C:\hostedtoolcache\windows\Ruby\3.4.4\x64\msys64\ucrt64\include\openblas"
          bundle exec rake test

  build-mac:
    runs-on: macos-latest
    name: Ruby 3.4 (macOS)
    steps:
    - uses: actions/checkout@v5
    - name: Install OpenBLAS
      run: |
        brew update
        brew install openblas
        brew info openblas
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake compile -- --with-opt-dir=/usr/local/opt/openblas
        bundle exec rake test
